from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(0, 0, 121, 31))
        self.mainLabel.setObjectName("mainLabel")
        self.advancedButton = QtWidgets.QPushButton(self.centralwidget)
        self.advancedButton.setGeometry(QtCore.QRect(0, 30, 101, 23))
        self.advancedButton.setObjectName("advancedButton")
        self.searchLabel = QtWidgets.QLabel(self.centralwidget)
        self.searchLabel.setGeometry(QtCore.QRect(10, 60, 141, 16))
        self.searchLabel.setObjectName("searchLabel")
        self.searchCombobox = QtWidgets.QComboBox(self.centralwidget)
        self.searchCombobox.setGeometry(QtCore.QRect(160, 60, 171, 22))
        self.searchCombobox.setObjectName("searchCombobox")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(340, 60, 75, 23))
        self.searchButton.setObjectName("searchButton")
        self.sortCombobox = QtWidgets.QComboBox(self.centralwidget)
        self.sortCombobox.setGeometry(QtCore.QRect(460, 60, 171, 22))
        self.sortCombobox.setObjectName("sortCombobox")
        self.sortCombobox.addItem("Insertion Sort")
        self.sortCombobox.addItem("Merge Sort")
        self.sortCombobox.addItem("Bubble Sort")
        self.sortCombobox.addItem("Selection Sort")
        self.sortCombobox.addItem("Heap Sort")
        self.sortCombobox.addItem("Quick Sort")
        self.sortCombobox.addItem("PigeonHole Sort")
        self.sortCombobox.addItem("Shell Sort")
        self.sortCombobox.addItem("Tim Sort")
        self.sortCombobox.addItem("Counting Sort")
        self.sortCombobox.addItem("Radix Sort")
        self.sortCombobox.addItem("Bracket Sort")
        self.sortCombobox.addItem("odd-even Sort")
        self.sortButton = QtWidgets.QPushButton(self.centralwidget)
        self.sortButton.setGeometry(QtCore.QRect(640, 60, 75, 23))
        self.sortButton.setObjectName("sortButton")
        self.ScrappingLabel = QtWidgets.QLabel(self.centralwidget)
        self.ScrappingLabel.setGeometry(QtCore.QRect(10, 400, 61, 16))
        self.ScrappingLabel.setObjectName("ScrappingLabel")
        self.urlLabel = QtWidgets.QLabel(self.centralwidget)
        self.urlLabel.setGeometry(QtCore.QRect(10, 430, 51, 16))
        self.urlLabel.setObjectName("urlLabel")
        self.urlTextbox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.urlTextbox.setGeometry(QtCore.QRect(80, 430, 301, 21))
        self.urlTextbox.setObjectName("urlTextbox")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(390, 430, 75, 23))
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(480, 430, 75, 23))
        self.stopButton.setObjectName("stopButton")
        self.csvButton = QtWidgets.QPushButton(self.centralwidget)
        self.csvButton.setGeometry(QtCore.QRect(610, 400, 81, 23))
        self.csvButton.setObjectName("csvButton")
        self.excelButton = QtWidgets.QPushButton(self.centralwidget)
        self.excelButton.setGeometry(QtCore.QRect(700, 400, 81, 23))
        self.excelButton.setObjectName("excelButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(60, 510, 631, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 100, 751, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainLabel.setText(_translate("MainWindow", "Find medicines you need:"))
        self.advancedButton.setText(_translate("MainWindow", "Advanced Search"))
        self.searchLabel.setText(_translate("MainWindow", "name"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.sortButton.setText(_translate("MainWindow", "Sort"))
        self.ScrappingLabel.setText(_translate("MainWindow", "Scrapping"))
        self.urlLabel.setText(_translate("MainWindow", "Enter URL:"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.csvButton.setText(_translate("MainWindow", "Export to csv"))
        self.excelButton.setText(_translate("MainWindow", "Export to excel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Names"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Old Price"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Price"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stars"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Orders"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Discount"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", " Descriptiton"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Column"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())